language: node_js
sudo: false
node_js:
  - 9
install:
  - yarn
script:
  - yarn tslint
  # Run test before build. Build takes a while due to compression step, so we want to fail fast.
  - yarn test
  - yarn build
cache: yarn
before_deploy:
  - openssl aes-256-cbc -K $encrypted_30952aa550a8_key -iv $encrypted_30952aa550a8_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
addons:
  ssh_known_hosts:
    - buttplug.world
deploy:
  - provider: script
    skip-cleanup: true
    script: rsync -r --quiet --delete-after deploy/* buttplugworld@buttplug.world:/home/buttplugworld/buttplug.world/syncydink
    on:
      branch: release
  - provider: script
    skip-cleanup: true
    script: rsync -r --quiet --delete-after deploy/* buttplugworld@buttplug.world:/home/buttplugworld/beta.buttplug.world/syncydink
    on:
      branch: beta
  - provider: pages
    skip-cleanup: true
    local-dir: deploy
    github-token: $GITHUB_TOKEN
    on:
      branch: master
